<?php
// Plugin definition
$plugin = array(
  'title' => t('jazzy'),
  'icon' => 'jazzy.png',
  'category' => t('Jazzy'),
  'css' => 'jazzy.css',
  'theme' => 'jazzy',
  'regions' => array(
  	'about2' => t('About Main'),
    'gallery1' => t('Gallery'),
    'order' => t('Order Top'),
    'order1' => t('Order Top 1'),
    'order2' => t('Order Top 2'),
    'ordermid' => t('Order Mid'),
    'order3' => t('Order Mid 1'),
    'order4' => t('Order Mid 2'),
    'orderbottom' => t('Order Bottom'),
    'order5' => t('Order Bottom 1'),
    'order6' => t('Order Bottom 2'),
    'ordercolor' => t('Order Colors'),
    'custom1' => t('Custom'),
  ),
);
